### ISSUE TITLE
Unable to import plugin

### ISSUE THREAD

**Issue by FromNetToDev** [netbox-community/netbox-qrcode#85]
Hello, when install this plugin I got this error
`(venv) root@netbox:/opt/netbox/netbox# source /opt/netbox/venv/bin/activate
(venv) root@netbox:/opt/netbox/netbox# pip install netbox-qrcode
Requirement already satisfied: netbox-qrcode in /opt/netbox-4.1.0/venv/lib/python3.10/site-packages (0.0.13)
Requirement already satisfied: qrcode in /opt/netbox-4.1.0/venv/lib/python3.10/site-packages (from netbox-qrcode) (7.4.2)
Requirement already satisfied: Pillow in /opt/netbox-4.1.0/venv/lib/python3.10/site-packages (from netbox-qrcode) (10.4.0)
Requirement already satisfied: typing-extensions in /opt/netbox-4.1.0/venv/lib/python3.10/site-packages (from qrcode->netbox-qrcode) (4.12.2)
Requirement already satisfied: pypng in /opt/netbox-4.1.0/venv/lib/python3.10/site-packages (from qrcode->netbox-qrcode) (0.20220715.0)
(venv) root@netbox:/opt/netbox/netbox# python3 /opt/netbox/netbox/manage.py migrate
Traceback (most recent call last):
  File "/opt/netbox-4.1.0/netbox/netbox/settings.py", line 795, in <module>
    plugin = importlib.import_module(plugin_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'netbox-qrcode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/core/management/base.py", line 104, in wrapper
    saved_locale = translation.get_language()
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 211, in get_language
    return _trans.get_language()
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 66, in __getattr__
    if settings.USE_I18N:
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in __getattr__
    self._setup(name)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 76, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/netbox-4.1.0/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox-4.1.0/netbox/netbox/settings.py", line 798, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Unable to import plugin netbox-qrcode: Module not found. Check that the plugin module has been installed within the correct Python environment.`

netbox version 4.1.0

**Comment by remram44** [comment]
You probably put `netbox-qrcode` instead of `netbox_qrcode` in your config

**Comment by cruse1977** [comment]
At the time of raising the readme stated there was no support for NetBox v4.1 - v0.0.15 provides this, closing this issue
